CREATE TABLE state (
id_state TINYINT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
description VARCHAR(100));

INSERT INTO state
VALUES (1, 'Project', 'This state is for new tasks');
INSERT INTO state
VALUES (2, 'In progress', 'This state is for tasks which have AT LEAST one completed operation');
INSERT INTO state
VALUES (3, 'Completed', 'This state is for tasks with all operations completed');

CREATE TABLE task (
id_task INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description VARCHAR(300) NOT NULL,
price INTEGER DEFAULT 0,
id_state TINYINT NOT NULL,
creation_date DATE NOT NULL,
completion_date DATE,
CONSTRAINT FK_task_state FOREIGN KEY (id_state)
    REFERENCES state(id_state)
);

CREATE TABLE task_operation (
id_task_operation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_task INTEGER NOT NULL,
description VARCHAR(300) NOT NULL,
planned_quantity INTEGER NOT NULL,
actual_quantity INTEGER,
price INTEGER NOT NULL,
total_cost INTEGER NOT NULL,
id_state TINYINT,
creation_date DATE,
completion_date DATE,
CONSTRAINT FK_task FOREIGN KEY (id_task) REFERENCES task(id_task),
CONSTRAINT FK_operation_state FOREIGN KEY (id_state) REFERENCES state(id_state),
);